// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtwBxdYezW5NWPhyw6Wnn_4lSgM1cdkO4',
    appId: '1:215160378670:web:49a863bc5ea0ef64ccd6bf',
    messagingSenderId: '215160378670',
    projectId: 'car-rental-app-4c9c4',
    authDomain: 'car-rental-app-4c9c4.firebaseapp.com',
    storageBucket: 'car-rental-app-4c9c4.appspot.com',
    measurementId: 'G-X1Y0GGEX12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJHxNwf8WMnDsgjzuNhCA8I1ObddE0o5c',
    appId: '1:215160378670:android:f57a79fa164c4bbfccd6bf',
    messagingSenderId: '215160378670',
    projectId: 'car-rental-app-4c9c4',
    storageBucket: 'car-rental-app-4c9c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEeHEnce42AUUG0lMi61ezblv33I7Idxs',
    appId: '1:215160378670:ios:e41c6e9ea6790d94ccd6bf',
    messagingSenderId: '215160378670',
    projectId: 'car-rental-app-4c9c4',
    storageBucket: 'car-rental-app-4c9c4.appspot.com',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEeHEnce42AUUG0lMi61ezblv33I7Idxs',
    appId: '1:215160378670:ios:e41c6e9ea6790d94ccd6bf',
    messagingSenderId: '215160378670',
    projectId: 'car-rental-app-4c9c4',
    storageBucket: 'car-rental-app-4c9c4.appspot.com',
    iosBundleId: 'com.example.carRentalApp',
  );
}
